version: "3.7"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "server"
    volumes:
      - ./web:/app:rw
    stdin_open: true
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - "db"
    volumes:
      - ./server:/app:rw